LIBS = /usr2/fs/poclb/poclb.a /usr2/fs/port/port.a /usr2/fs/clib/clib.a /usr2/fs/rtelb/rtelb.a -lm -lpthread -ljansson



OBJECTS = fsbridge.o

../bin/fsbridge : $(OBJECTS) $(LIBS)

include /usr2/fs/include.mk
